version: '3.8'
services:
  db:
    volumes:
      - /home/rpi5-8gb/klg:/var/lib/postgresql/data
    image: postgres:alpine3.18
    ports:
      - "5439:5432"
    restart: always
    environment:
      POSTGRES_DB: klg_client
      POSTGRES_USER: klg_client
      POSTGRES_PASSWORD: klg_client
    networks:
      - default

  redis:
    restart: always
    image: 'redis:latest'
    ports:
      - 6379:6379