version: '3.8'
services:
  db:
    image: postgres:alpine3.18
    ports:
      - "5439:5432"
    restart: always
    environment:
      POSTGRES_DB: klg_client
      POSTGRES_USER: klg_client
      POSTGRES_PASSWORD: klg_client
    networks:
      - default